# Generated by Django 5.0.4 on 2024-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('text', models.TextField(verbose_name='содержание')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('publication', models.BooleanField(default=False, verbose_name='публикация')),
                ('view_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
