# Generated by Django 4.2.2 on 2024-05-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_title', 'Can edit title'), ('can_edit_text', 'Can edit text'), ('can_edit_publication', 'Can edit publication')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
