# Generated by Django 5.0.4 on 2024-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='', verbose_name='Дата производства'),
        ),
    ]
