# Generated by Django 4.2.2 on 2024-05-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publication', 'Can edit publication')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
